apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost.fullname" . }}
  labels:
    app.kubernetes.io/component: ghost
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: ghost
        {{- include "ghost.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ghost.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if or (not .Values.externalDatabase.existingSecret) (not .Values.ghost.smtp.existingSecret) }}
          envFrom:
            - secretRef:
                name: {{ include "ghost.fullname" . }}-db
            - secretRef:
                name: {{ include "ghost.fullname" . }}-smtp
          {{- end }}

          env:
            - name: url
              value: {{ .Values.ghost.url }}

            - name: admin__url
              value: {{ .Values.ghost.admin_url }}

            - name: DOMAIN
              value: {{ .Values.ghost.domain }}

            - name: ADMIN_DOMAIN
              value: {{ .Values.ghost.admin_domain }}

            - name: logging__level
              value: {{ .Values.ghost.logging_level }}

            - name: database__client
              value: mysql

            - name: ACTIVITYPUB_TARGET
              value: "{{ include "ghost.fullname" . }}-activitypub.{{ .Release.Namespace }}.svc:{{ .Values.activity_pub.service.port }}"

            {{- if .Values.externalDatabase.existingSecret }}
            - name: database__connection__host
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret }}
                  key: {{ .Values.externalDatabase.secretKeys.hostname }}

            - name: database__connection__port
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret }}
                  key: {{ .Values.externalDatabase.secretKeys.port }}

            - name: database__connection__database
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret }}
                  key: {{ .Values.externalDatabase.secretKeys.database }}

            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret }}
                  key: {{ .Values.externalDatabase.secretKeys.username }}

            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret }}
                  key: {{ .Values.externalDatabase.secretKeys.password }}

            - name: DATABASE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret }}
                  key: {{ .Values.externalDatabase.secretKeys.root_password }}
            {{- end }}

            {{- if .Values.ghost.smtp.existingSecret }}
            - name: mail__options__host
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.smtp.existingSecret }}
                  key: {{ .Values.ghost.smtp.secretKeys.host }}

            - name: mail__options__port
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.smtp.existingSecret }}
                  key: {{ .Values.ghost.smtp.secretKeys.port }}

            - name: mail__transport
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.smtp.existingSecret }}
                  key: {{ .Values.ghost.smtp.secretKeys.protocol }}

            - name: mail__from
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.smtp.existingSecret }}
                  key: {{ .Values.ghost.smtp.secretKeys.from_address }}

            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.smtp.existingSecret }}
                  key: {{ .Values.ghost.smtp.secretKeys.username }}

            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.smtp.existingSecret }}
                  key: {{ .Values.ghost.smtp.secretKeys.password }}
            {{ end }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/ghost/content
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "ghost.fullname" . }}
            {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
