{{- if .Values.proxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-nginx-proxy
  labels:
    app.kubernetes.io/component: proxy
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: proxy
        {{- include "ghost.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: nginx
              containerPort: 80

          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true

          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 1000m
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
{{- end }}
