{{- if eq .Values.proxy.enabled true }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  {{- with .Values.proxy.config }}
  nginx.conf:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

