{{- if eq .Values.proxy.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.fullname" . }}-proxy
  labels:
    app.kubernetes.io/component: ghost
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "ghost.selectorLabels" . | nindent 4 }}
{{- end }}
