---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-nginx-proxy
spec:
  selector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 4 }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ghost
        {{- include "ghost.labels" . | nindent 4 }}
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: nginx
              containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 1000m
          livenessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders: []
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
