{{- if not .Values.activity_pub.externalDatabase.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.fullname" . }}-activitypub-db
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
    app.kubernetes.io/component: activitypub
data:
  MYSQL_HOST: {{ .Values.activity_pub.externalDatabase.host | b64enc }}
  MYSQL_PORT: {{ .Values.activity_pub.externalDatabase.port| quote | b64enc }}
  MYSQL_DATABASE: {{ .Values.activity_pub.externalDatabase.database | b64enc }}
  MYSQL_USER: {{ .Values.activity_pub.externalDatabase.username | b64enc }}
  MYSQL_PASSWORD: {{ .Values.activity_pub.externalDatabase.password | b64enc }}
  DATABASE_ROOT_PASSWORD: {{ .Values.activity_pub.externalDatabase.root_password | b64enc }}
  # mysql connection string.
  MYSQL_CONNECTION_STRING: {{ printf "mysql://%s:%s@tcp(%s:%s)/%s" .Values.activity_pub.externalDatabase.username (.Values.activity_pub.externalDatabase.password | urlquery) .Values.activity_pub.externalDatabase.host .Values.activity_pub.externalDatabase.port .Values.activity_pub.externalDatabase.database | b64enc }}
{{- end }}
