{{- if not .Values.ghost.admin.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.fullname" . }}-admin-credentials
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
data:
  GHOST_USERNAME: {{ .Values.ghost.admin.username | b64enc }}
  GHOST_PASSWORD: {{ .Values.ghost.admin.password | b64enc }}
{{- end }}
