{{- if not .Values.ghost.smtp.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.fullname" . }}-smtp
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
data:
  mail__options__host: {{ .Values.ghost.smtp.host | b64enc }}
  mail__options__port: {{ .Values.ghost.smtp.port | b64enc }}
  mail__options__auth__user: {{ .Values.ghost.smtp.username | b64enc }}
  mail__options__auth__pass: {{ .Values.ghost.smtp.password | b64enc }}
  mail__transport: {{ .Values.ghost.smtp.protocol | b64enc }}
{{- end }}
